### ISSUE TITLE
Error when training with custom dataset

### ISSUE THREAD

**Issue by BobbleHeadAlien** [meijieru/crnn.pytorch#138]
Hi @meijieru 
 
I have created a dataset using the mjsynth data following the instructions from the original repo as mentioned. This gave me two files namely "data.mdb" and "lock.mdb" I saved it into a folder and used this path to run the crnn_main.py. 

Initially I got an error message with respect to the dataset.py folder as follows,

> File "/home/ubuntu-andrea/CRNN2/crnn.pytorch/dataset.py", line 32, in init
> nSamples = int(txn.get('num-samples'))
> TypeError: Won't implicitly convert Unicode to bytes; use .encode()

I solved it following [this thread](https://github.com/meijieru/crnn.pytorch/issues/38)

I made the required changes to the dataset file. but now im getting the below error:

> Traceback (most recent call last):
> File "crnn_main.py", line 59, in 
> train_dataset = dataset.lmdbDataset(root=opt.trainroot)
> File "/new/Kaushik/crnn.pytorch_1/dataset.py", line 32, in init
> nSamples = int(txn.get('num-samples'.encode()))
> ValueError: invalid literal for int() with base 10: b''

Can anyone please tell me why im getting this? I know that we get this message when the int contains either a non-int character or is empty.
I am using python 3.6 and pytorch 0.4.

Please help me out here. thankyou.

**Comment by BobbleHeadAlien** [comment]
I have solved the issue. thanks

**Comment by huiyang865** [comment]
I also get the similar error: 
Traceback (most recent call last):
  File "/home/robert/Documents/crnn.pytorch/crnn_main.py", line 199, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "/home/robert/Documents/crnn.pytorch/crnn_main.py", line 178, in trainBatch
    t, l = converter.encode(cpu_texts)
  File "/home/robert/Documents/crnn.pytorch/utils.py", line 51, in encode
    text, _ = self.encode(text)
  File "/home/robert/Documents/crnn.pytorch/utils.py", line 45, in encode
    for char in text
  File "/home/robert/Documents/crnn.pytorch/utils.py", line 45, in <listcomp>
    for char in text
KeyError: 'b'

How do u solve the issue?

**Comment by Kumara-Kaushik** [comment]
Can you give me more details as to which version of python and pytorch are you using and which dataset are you using?

**Comment by huxb23** [comment]
@huiyang865 you  solve the issue？
@Kumara-Kaushik  python =3.6.2 pytorch =0.4.0 
thankyou

**Comment by Kumara-Kaushik** [comment]
This entire encode, decode error happens because in python two, strings are encoded into binary type by default. so no need to use commands like encode() and decode() explicitly. But in python 3 you have to explicitly encode and decode the strings as it does not do it by default. 

What I suggest you to do is use python debugger and run the code line by line and find out if the outputs at each line of code is as expected. 

The most common cause of such errors will be because the code might not have generated a binary format for a value or a binary format would not have been decoded in the right place. 

If you dont know how to use a python debugger, I highly recommend you learn how to use it. It is a very useful tool when coding.

**Comment by jamesbondzhou** [comment]
hi,Initially I got an error message with respect to the dataset.py folder as follows,
nSamples = int(txn.get('num-samples'))
TypeError: Won't implicitly convert Unicode to bytes; use .encode()

so i changed like this: nSamples = int(txn.get(('num-samples').encode('utf-8'))).
but another error occurs:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
can someone help me ?
