### ISSUE TITLE
cublas runtime error： the GPU program failed to execute

### ISSUE THREAD

**Issue by wjbKimberly** [meijieru/crnn.pytorch#28]
I run crnn_main.py by this command:

`python crnn_main.py --trainroot="/home/wangjianbo_i/OCR/data/IIIT5K/traindatalmdb" --valroot="/home/wangjianbo_i/OCR/data/IIIT5K/testdatalmdb" --cuda --alphabet="0123456789abcdefghijklmnopkrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ,;:" --imgH=32`

And the error message shows below. I tried to run it on the company's server to avoid the environment error, but get the same result. How to solve this problem? :-D
![2017-06-07 16-23-38](https://user-images.githubusercontent.com/23569606/26869073-ae87d658-4b9d-11e7-9cf8-184ca12371d7.png)

**Comment by meijieru** [comment]
It seems to be a problem of `PyTorch`. You could better ask in the forum of [it](https://discuss.pytorch.org/)

**Comment by wjbKimberly** [comment]
☆⌒(*＾-゜)v THX!!

**Comment by ahmedmazari-dhatim** [comment]
@wjbKimberly , how run this code with alphabet ={abcdefghijklmnopkrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ} such that the program lowercase all the uppercase chars ?

Thank you

**Comment by lijian-1994** [comment]
@wjbKimberly I met the same error.How do you solve it? Thanks!

**Comment by uzl** [comment]
I **fixed** this problem by doing *dataset label* correction. 
I mean, *training label* was incorrect for my dataset. for example: because of my encoding problem, I had to fix in `line: 61` in `dataset.py`
```
label = txn.get(label_key.encode())
label = label.decode()
``` . 

Please first check your expected label inside `cpu_texts` variable from `cpu_images, cpu_texts = data` *(line 174 in train.py )*
